import random
import sqlite3

fnames = ['Emma', 'Liam', 'Olivia', 'Noah', 'Ava', 'Oliver', 'Isabella', 'Elijah', 'Sophia', 'James', 'Mia', 'William', 'Amelia', 'Benjamin', 'Harper', 'Lucas', 'Evelyn', 'Henry', 'Abigail', 'Alexander', 'Ella', 'Jackson', 'Scarlett', 'Sebastian', 'Grace', 'Aiden', 'Chloe', 'Matthew', 'Aria', 'Daniel', 'Zoe', 'Michael', 'Lily', 'Ethan', 'Nora', 'Jacob', 'Riley', 'Logan', 'Layla', 'David', 'Sofia', 'Joseph', 'Audrey', 'Samuel', 'Bella', 'Carter', 'Aubrey', 'Owen', 'Hannah', 'Wyatt', 'Addison', 'John', 'Natalie', 'Luke', 'Lucy', 'Isaac', 'Mila', 'Gabriel', 'Ellie', 'Anthony', 'Stella', 'Dylan', 'Luna', 'Leo', 'Savannah', 'Jaxon', 'Brooklyn', 'Julian', 'Claire', 'Grayson', 'Skylar', 'Asher', 'Victoria', 'Christopher', 'Madison', 'Josiah', 'Peyton', 'Andrew', 'Kinsley', 'Thomas', 'Naomi', 'Charles', 'Aaliyah', 'Caleb', 'Elena', 'Hunter', 'Violet', 'Isaiah', 'Lydia', 'Eli', 'Samantha', 'Aaron', 'Addilyn', 'Nolan', 'Mackenzie', 'Adam', 'Kaylee', 'Jace', 'Gianna', 'Zachary', 'Ariana', 'Miles', 'Kylie', 'Jasper', 'Emery', 'Xavier', 'Sophie', 'Landon', 'Jasmine', 'Ryder', 'Alyssa', 'Colton', 'Katherine', 'Jett', 'Maya']
lnames = ['Smith', 'Johnson', 'Williams', 'Jones', 'Brown', 'Davis', 'Miller', 'Wilson', 'Moore', 'Taylor', 'Anderson', 'Thomas', 'Jackson', 'White', 'Harris', 'Martin', 'Thompson', 'Garcia', 'Martinez', 'Robinson', 'Clark', 'Rodriguez', 'Lewis', 'Lee', 'Walker', 'Hall', 'Allen', 'Young', 'Hernandez', 'King', 'Wright', 'Lopez', 'Hill', 'Scott', 'Green', 'Adams', 'Baker', 'Gonzalez', 'Nelson', 'Carter', 'Mitchell', 'Perez', 'Roberts', 'Turner', 'Phillips', 'Campbell', 'Parker', 'Evans', 'Edwards', 'Collins', 'Stewart', 'Sanchez', 'Morris', 'Rogers', 'Reed', 'Cook', 'Morgan', 'Bell', 'Murphy', 'Bailey', 'Rivera', 'Cooper', 'Richardson', 'Cox', 'Howard', 'Ward', 'Torres', 'Peterson', 'Gray', 'Ramirez', 'James', 'Watson', 'Brooks', 'Kelly', 'Sanders', 'Price', 'Bennett', 'Wood', 'Barnes', 'Ross', 'Henderson', 'Coleman', 'Jenkins', 'Perry', 'Powell', 'Long', 'Patterson', 'Hughes', 'Flores', 'Washington', 'Butler', 'Simmons', 'Foster', 'Gonzales', 'Bryant', 'Alexander', 'Russell', 'Griffin', 'Diaz', 'Hayes', 'Myers', 'Ford', 'Hamilton', 'Graham', 'Sullivan', 'Wallace', 'Woods', 'Cole', 'West', 'Jordan', 'Owens', 'Reynolds', 'Fisher', 'Ellis', 'Harrison', 'Gibson', 'McDonald', 'Cruz', 'Marshall', 'Ortiz', 'Gomez', 'Murray', 'Freeman', 'Wells', 'Webb', 'Simpson', 'Stevens', 'Tucker', 'Porter', 'Hunter', 'Hicks', 'Crawford', 'Henry', 'Boyd', 'Mason', 'Morales', 'Kennedy', 'Warren', 'Dixon', 'Ramos', 'Reyes', 'Burns', 'Holt', 'Vasquez', 'Snyder', 'Simpson', 'Cameron', 'Pope', 'Mills', 'Norris', 'Stanley', 'Caldwell', 'Lowe', 'Lindsay', 'Hodge', 'Hodge', 'Hodge']
make = ['Toyota', 'Ford', 'Chevrolet', 'Honda', 'Nissan', 'BMW', 'Mercedes-Benz', 'Volkswagen', 'Hyundai', 'Kia', 'Subaru', 'Mazda', 'Audi', 'Lexus', 'Dodge', 'Chrysler', 'Jeep', 'GMC', 'Buick', 'Land Rover', 'Porsche', 'Jaguar', 'Volvo', 'Fiat', 'Tesla', 'Acura', 'Infiniti', 'Mitsubishi', 'Mini', 'Ram', 'Lincoln', 'Cadillac', 'Alfa Romeo', 'Bentley', 'Rolls-Royce', 'Aston Martin', 'McLaren', 'Bugatti', 'Lamborghini', 'Ferrari', 'Peugeot', 'Renault', 'Citroën', 'Skoda', 'Seat', 'Opel', 'Saab', 'Chrysler', 'Smart', 'Daihatsu', 'Isuzu', 'Suzuki', 'Tata', 'Mahindra', 'Geely', 'BYD', 'Changan', 'Great Wall', 'NIO', 'Rivian', 'Lucid', 'Polestar', 'Fisker', 'Faraday Future', 'Wuling', 'Zotye', 'Lynk & Co', 'Xpeng', 'MG', 'Aston Martin', 'Pagani', 'Koenigsegg', 'Lotus', 'Spyker', 'Caterham', 'Morgan', 'Noble', 'TVR', 'Plymouth', 'Scion', 'Hummer', 'Saturn', 'Oldsmobile', 'Pontiac', 'Datsun', 'Lancia', 'Alpina', 'Bristol', 'Rover', 'Tucker', 'DeLorean', 'Panoz', 'Saleen', 'Vector', 'Ariel', 'Radical', 'Caterham', 'Donkervoort', 'Ginetta', 'Noble', 'Wiesmann']
model = ['Camry', 'F-150', 'Silverado', 'Civic', 'Altima', '3 Series', 'C-Class', 'Golf', 'Elantra', 'Sorento', 'Outback', 'CX-5', 'A4', 'RX', 'Silverado', 'Charger', '300', 'Wrangler', 'Sierra', 'Enclave', 'Range Rover', '911', 'F-Type', 'XC90', '500', 'Model S', 'MDX', 'Q50', 'Outlander', 'Cooper', '1500', 'Navigator', 'Escalade', 'Giulia', 'Continental', 'Bentayga', 'Phantom', 'DB11', '720S', 'Chiron', 'Huracán', '488', '208', 'Clio', 'C3', 'Octavia', 'Leon', 'Astra', '9-3', 'Fortwo', 'Terios', 'D-Max', 'Swift', 'XUV500', 'Tiggo', 'Han', 'P7', 'R1T', 'Air', '2', 'C40', 'F-PACE', 'DBX', 'Vantage', 'Z4', 'M3', 'Civic Type R', 'Mustang', 'Challenger', 'Corvette', 'GTR', 'Supra', 'S2000', 'Z', 'Rogue', 'Kona', 'Tucson', 'RAV4', 'CR-V', 'Qashqai', 'C-HR', 'Seltos', 'Soul', 'Forte', 'Optima', 'Sonata', 'Tiguan', 'Atlas', 'Passat', 'Jetta', 'A3', 'Q3', 'Q5', 'A6', 'A8', 'S60', 'V60', 'C70', 'XC60', 'XC40', 'Civic Si', 'Accord', 'Fit', 'Insight', 'CR-Z', 'RDX', 'TLX', 'ILX', 'ZDX', 'Rogue Sport', 'Murano', 'Pathfinder', 'Armada', 'Maxima', '370Z', 'Altima Coupe', 'Versa', 'Sentra', 'Leaf', 'Kicks', 'Juke', 'Murano']
role = ['staff','visitor','student']
def generatecaregistrations(x):
    Uletters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    Numbers = '0123456789'
    conn = sqlite3.connect('car-info.db')
    c = conn.cursor()
    c.execute('CREATE TABLE IF NOT EXISTS car-info (PersonID INT PRIMARY KEY, Make TEXT, Model TEXT, 


def generatepermits():
    connpermit = sqlite3.connect('permit.db')
    cpermit = connpermit.cursor()
    cpermit.execute('CREATE TABLE IF NOT EXISTS permits (Registration  PRIMARY KEY